package com.group9.asaa.classes.transport

enum class ReceiverState {
    START, RECEIVING_ORDER, RECEIVED_ORDER, TIMED_OUT,
    CHECKING_AVAILABILITY, SENDING_CONFIRMATION,
    DENYING_ORDER, ACCEPTING_ORDER, ORDER_ACCEPTED,
    FULFILLING_ORDER, NOTIFYING_STATUS_FULFILLING_ORDER,
    ORDER_FULFILLED, NOTIFYING_STATUS_FULFILLED,
    SENT_CONFIRMATION, NOTIFYING_NOT_AVAILABLE,
    NOTIFYING_STATUS_NOT_AVAILABLE, DONE
}
