package com.group9.asaa.classes.transport

enum class TransportSystemState {
    IDLE,
    CREATING_ORDER, ORDER_CREATED, SENDING_ORDER,
    AWAITING_CONFIRMATION, EVALUATING_CONFIRMATION,
    ORDER_ACCEPTED, ACQUIRING_AGV, AGV_ACQUIRED,
    PERFORMING_TRANSPORT, TRANSPORT_COMPLETED,
    ORDER_COMPLETED, ORDER_DENIED, ORDER_TIMED_OUT,
    AGV_UNAVAILABLE, FULFILLING_ORDER
}