package com.group9.asaa.classes.assembly

enum class AssemblySystemStates {
    IDLE,
    CREATING_ORDER,
    ORDER_CREATED,
    SENDING_ORDER,
    RECEIVING_CONFIRMATION,
    ORDER_TIMED_OUT,
    EVALUATING_CONFIRMATION,
    ORDER_DENIED,
    ORDER_ACCEPTED,
    WAITING_FOR_TRANSPORT,
    ASSEMBLING,
    ASSEMBLY_TIMED_OUT,
    ASSEMBLY_COMPLETED,
    ASSEMBLY_INVALID,
    NOTIFYING_STATUS
}
